### ISSUE TITLE
adjust Top Bar Size

### ISSUE THREAD

**Issue by Designator-Ol** [ART3MISTICAL/dotfiles#1]
Hi ART3MISTICAL,

this is not really an issue but more a question by me.
How would I change the size of the top bar or in other words what config file do I need to edit to adjust the hight and width of the top bar ?

Your help is highly appreciated.

Greetz Desi

**Comment by devansharora18** [comment]
edit line number 2472 of gnome-shell.css in theme
increase/decrease height and increase/decrease left/right padding for changing the width
