### ISSUE TITLE
Gnome 44 incompatabilty issue in top bar

### ISSUE THREAD

**Issue by zeninit0** [ART3MISTICAL/dotfiles#2]
Hello, I use your Catppuccino-Mocha theme on my Gnome Arch system. My system recently received a Gnome 44.1 update, and as a result, the alignment of the drop-down's wifi, Bluetooth, and other options is now messed up. The image is attached. kindly check or update where I can make the changes. Thank you.
![Screenshot from 2023-05-16 16-03-50](https://github.com/ART3MISTICAL/dotfiles/assets/65948438/a85da609-1e83-4ef9-bdbe-0a2000014912)

**Comment by devansharora18** [comment]
fixed it
